# Generated by Django 4.2.9 on 2024-03-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
