# Generated by Django 4.2.9 on 2024-03-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('api', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
