# Generated by Django 4.2.9 on 2024-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='keywords',
            field=models.CharField(default='calm', max_length=500),
            preserve_default=False,
        ),
    ]
